version: '3.8'
services:
  api:
    image: eslih/basic-webapp-api:v1.1.1
    build: ./api
    expose:
      - 8080
    depends_on:
      - postgres
    environment:
      - PG_PASSWORD=student_password
      - PG_USER=student_user
      - PG_DATABASE=labo
      - PG_PORT=5432
      - PG_HOST=postgres
      - PORT=8080
  webapp:
    image: eslih/basic-webapp-frontend:v1.1.1
    build: ./web
    command: uwsgi --ini app.ini
    expose:
      - 5000
    depends_on:
      - api
    volumes:
    - statics:/app/webapp/static:ro
  nginx:
    image: eslih/basic-webapp-nginx:v1.1.1
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - webapp
    volumes:
    - statics:/app/static:ro
  postgres:
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_PASSWORD=student_password
      - POSTGRES_USER=student_user
      - POSTGRES_DB=labo
    volumes:
      - postgres:/var/lib/postgresql/data/
volumes:
  statics:
  postgres: